version: "3"

tasks:
  build:
    desc: Build the server binary
    deps:
      - test
      - lint
    cmds:
      - go build -o build/gocommender ./cmd/server

  build-linux:
    desc: Build for Linux
    deps:
      - test
      - lint
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -o build/gocommender-linux ./cmd/server

  build-ci:
    desc: Build for CI environment
    deps:
      - test-ci
      - lint
    cmds:
      - go build -o build/gocommender-ci ./cmd/server

  test:
    desc: Run unit tests (excludes integration tests)
    cmds:
      - go test -short -v ./...

  test-ci:
    desc: Run tests with coverage for CI
    cmds:
      - go test -tags=ci -cover -v ./...

  test-integration:
    desc: Run integration tests
    cmds:
      - go test -v -tags=integration ./...

  test-all:
    desc: Run all tests including integration tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Generate test coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  benchmark:
    desc: Run benchmarks
    cmds:
      - go test -bench=. -benchmem ./...

  lint:
    desc: Run linter
    cmds:
      - go fmt ./...
      - go vet ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build/*

  dev:
    desc: Run development server
    cmds:
      - go run ./cmd/server