version: "3"

tasks:
  build:
    desc: Build the server binary
    deps:
      - test
      - lint
    cmds:
      - go build -o build/gocommender ./cmd/server

  build-linux:
    desc: Build for Linux
    deps:
      - test
      - lint
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -o build/gocommender-linux ./cmd/server

  build-ci:
    desc: Build for CI environment
    cmds:
      - go build -o build/gocommender-ci ./cmd/server

  build-versioned:
    desc: Build with version information
    vars:
      VERSION: '{{.VERSION | default "dev"}}'
      COMMIT: '{{.COMMIT | default "unknown"}}'
      BUILD_DATE: '{{.BUILD_DATE | default "unknown"}}'
    cmds:
      - |
        go build -ldflags="-w -s -X main.Version={{.VERSION}} -X main.Commit={{.COMMIT}} -X main.BuildDate={{.BUILD_DATE}}" \
        -o build/gocommender-versioned ./cmd/server

  test:
    desc: Run unit tests (excludes integration tests)
    cmds:
      - go test -short -v ./...

  test-ci:
    desc: Run tests with coverage for CI
    cmds:
      - go test -tags=ci -cover -coverprofile=coverage.out -v ./...

  test-integration:
    desc: Run integration tests
    cmds:
      - go test -v -tags=integration ./...

  test-all:
    desc: Run all tests including integration tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Generate test coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  benchmark:
    desc: Run benchmarks
    cmds:
      - go test -bench=. -benchmem ./...

  lint:
    desc: Run linter
    cmds:
      - go fmt ./...
      - go vet ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build/*
      - cd web && npm run clean

  dev:
    desc: Run development server
    cmds:
      - go run ./cmd/server

  frontend-dev:
    desc: Run frontend development server
    dir: web
    cmds:
      - npm run dev

  frontend-build:
    desc: Build frontend for production
    dir: web
    cmds:
      - npm install
      - npm run build

  frontend-type-check:
    desc: Check TypeScript types in frontend
    dir: web
    cmds:
      - npm run type-check

  build-all:
    desc: Build both backend and frontend
    deps:
      - build
      - frontend-build